# https://binx.io/2021/02/28/the-simplest-and-most-generic-google-cloud-build-yaml-config-file-ever/

steps:
- name: '${_BUILD_IMAGE_PATH}'
  args:
    - "-m"
    - "poetry"
    - "version"
    - "$_VERSION"
  id: SetVersion
- name: '${_BUILD_IMAGE_PATH}'
  args:
    - "-m"
    - "poetry"
    - "install"
  id: Install
# - name: 'asia-south1-docker.pkg.dev/${PROJECT_ID}/sarvam-docker-ci/python-ci'
#   args:
#     - "-m"
#     - "poetry"
#     - "run"
#     - "test"
#   id: Test
- name: '${_BUILD_IMAGE_PATH}'
  args:
    - "-m"
    - "poetry"
    - "publish"
    - "--build"
    - "-r"
    - "google"
  id: PackageAndPublish

substitutions:
  _LOCATION: 'europe-west4'
  _DOCKER_REGISTRY_NAME: 'sarvam-docker-ci'
  _BUILD_IMAGE_NAME: 'python-ci'
  _BUILD_IMAGE_PATH: '${_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_DOCKER_REGISTRY_NAME}/${_BUILD_IMAGE_NAME}'
  _VERSION: $TAG_NAME

options:
  dynamic_substitutions: true

